### ISSUE TITLE
iosfw 0.9.6 ProcessLookupError

### ISSUE THREAD

**Issue by falz** [austind/iosfw#10]
Testing iosfw 0.9.6, I having errors. Nothing is logged to file on disk, only throwing:

```
$ python3
Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from iosfw import iosfw
>>> device = iosfw('dhcp-buildroom-7')
Exception ignored in: <bound method iosfw.__del__ of <iosfw.iosfw.iosfw object at 0x7f7eabaf17b8>>
Traceback (most recent call last):
  File "/opt/scripts/iosfw/iosfw/iosfw.py", line 227, in __del__
    except OSError.ProcessLookupError:
AttributeError: type object 'OSError' has no attribute 'ProcessLookupError'
>>> 
>>> 
KeyboardInterrupt
```

That error is in a function that's attempting to work around an ssh proxy, which we are not using. If it matters, I have these versions of related things installed:

napalm (3.0.1)
netmiko (3.1.1)
PyYAML (5.3.1)

If I switch back to the dev branch, which I was testing before a few recent bugfixes, it works fine.

**Comment by falz** [comment]
Ah, re-reading diffs, `device.open()` is a [new step](https://github.com/austind/iosfw/commit/60332a6eebb2fa53bb8580b5ca155704f29f4a9e)

testing this and expecting to work.

**Comment by austind** [comment]
I saw no problems on same python version.

**Comment by falz** [comment]
Was finally able to test. This does work now that I am using `device.open()`. 

Note per issue [9](https://github.com/austind/iosfw/issues/9), I did notice an unrelated regression in extra debug output in 0.9.6 in general, put a note there.
