### ISSUE TITLE
Working on Cisco device?

### ISSUE THREAD

**Issue by ezspot** [austind/iosfw#12]
Hi! 

Will this work on following: 
Cisco 4506
Cisco 9007
Cisco ASR 9001
Cisco ASR 9401

or maybe can recommend something. Would like a “version” check and upgrade system.

**Comment by falz** [comment]
No offense but.. please test with all devices and report back. If they run IOS or IOS-XE they likely should work.

**Comment by austind** [comment]
check the readme. ~~ASR/ISR not yet supported.~~ 4506/9007 untested. Accepting PRs.

Edit: my bad, some ISRs are supported. test on your platforms & report back.
