### ISSUE TITLE
Endless recursion on trying NTP Update

### ISSUE THREAD

**Issue by operatorofhell** [austind/iosfw#3]
Hi, 

in iosfw.py:825 there is a call for schedule_reload() within the definition. If the NTP sync doesn't happen the function will call itself until the end of days.

```
def schedule_reload(...)
[...]
 return self.schedule_reload()
[...]
```

Thanks for the neat piece of code

Moe

**Comment by austind** [comment]
Thanks for the report! I pushed a fix, let me know how it goes.
