### ISSUE TITLE
Hide output of config settings

### ISSUE THREAD

**Issue by falz** [austind/iosfw#9]
How does one hide the output of the python dictionary of the config file? I was doing testing via cli, but have moved to integrating it in to a script using [batch_example.py](https://github.com/austind/iosfw/blob/master/example/batch_example.py).

When I run it, I always get the full output of config.yaml dumped to console, as well as 

I've tried adjusting console_log_level from info to critical, and no luck in between. I've also changed log_method from tee to file, also with no changes at all.

**Comment by austind** [comment]
Temporary fix in latest dev commit

**Comment by falz** [comment]
tested, seemed to work great! I didnt put prior output originally, but it always had json dump of both the config file as well as another dump of the NAPAM options after asking for secret.

Fixed from my perspective.

```
$ ./upgrade-cisco.py 
Checking dhcp-buildroom-4 Type: ASR-920-4SZ-A Version OK: 16.9.5f
Checking dhcp-buildroom-3 Type: ASR-920-4SZ-A Version OK: 16.9.5f
Checking dhcp-buildroom-2 Type: ASR-920-4SZ-A Version OK: 16.9.5f
Checking dhcp-buildroom-5 Type: ASR-920-4SZ-A Version Mismatch! Device: 15.6(2)SP7 Desired: 16.9.5f
lets try to upgrade dhcp-buildroom-5
===============================================
Opening connection to dhcp-buildroom-5 via ssh...
Connected to available-device (ASR-920-4SZ-A) as netconf via ssh
Running version: 15.6(2)SP7
Upgrade version: 16.9.5f
Upgrade status: NEEDS UPGRADE
Starting upgrade on available-device at 15:12:34 2020-05-28...
Disabling line vty exec-timeout...
Checking free space...
Found enough free space!
Installing new firmware...
Starting transfer. Expect this to take several minutes...
Transfer complete! Verifying hash...
Hash verified!
Checking boot image...
Setting boot image to bootflash:/asr920-universalk9_npe.16.09.05f.SPA.bin...
Success! New boot image set to bootflash:/asr920-universalk9_npe.16.09.05f.SPA.bin.
Scheduling reload...
Restoring line vty exec-timeout...
Upgrade on available-device completed at 15:23:27 2020-05-28
Total time elapsed: 0:10:53.721641
````

**Comment by falz** [comment]
Note that i upgraded to 0.9.6 and still see some debug output, only from console.

My settings have both set to info:
file_log_level: info
console_log_level: info

But this outputs to console:
```
{'hostname': 'dhcp-buildroom-2',
 'optional_args': {'secret': '<redacted>',
                   'ssh_config_file': '~/.ssh/config',
                   'transport': 'ssh'},
 'password': '<redacted>',
 'timeout': 60,
 'username': 'netconf'}
```

**Comment by austind** [comment]
I caught this after the 0.9.6 tag, try the latest commit
